# This is the Makefile for Taylor UUCP
# $Id$

SUBDIR=		libunix libuucp libuuconf \
		doc sample \
		cu uuchk uucico uuconv uucp uulog uuname uupick uusched \
		uustat uuto uux uuxqt

.include <bsd.subdir.mk>
