#	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/libexec/uucpd/Makefile,v 1.10 1999/12/16 10:55:40 marcel Exp $

PROG=	uucpd
MAN8=	uucpd.8
LDADD=  -lcrypt -lutil
DPADD=  ${LIBCRYPT} ${LIBUTIL}
.include <bsd.prog.mk>
